In [1]:
import pandas as pd

In [2]:
state_pops_csv = "nst-est2019-01.csv"

In [3]:
state_populations = pd.read_csv(state_pops_csv)
state_populations.head(10)

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,1-Apr-10,NaN,Population Estimate (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
3,United States,"308,745,538","308,758,105","309,321,666","311,556,874","313,830,990","315,993,715","318,301,008","320,635,163","322,941,311","324,985,539","326,687,501","328,239,523"
4,Northeast,"55,317,240","55,318,443","55,380,134","55,604,223","55,775,216","55,901,806","56,006,011","56,034,684","56,042,330","56,059,240","56,046,620","55,982,803"
5,Midwest,"66,927,001","66,929,725","66,974,416","67,157,800","67,336,743","67,560,379","67,745,167","67,860,583","67,987,540","68,126,781","68,236,628","68,329,004"
6,South,"114,555,744","114,563,030","114,866,680","116,006,522","117,241,208","118,364,400","119,624,037","120,997,341","122,351,760","123,542,189","124,569,433","125,580,448"
7,West,"71,945,553","71,946,907","72,100,436","72,788,329","73,477,823","74,167,130","74,925,793","75,742,555","76,559,681","77,257,329","77,834,820","78,347,268"
8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"

In [4]:
state_pop1 = state_populations.drop([0,1,3,4,5,6,7])

In [5]:
state_pop1.head(10)

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
2,NaN,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"
10,Arizona,"6,392,017","6,392,288","6,407,172","6,472,643","6,554,978","6,632,764","6,730,413","6,829,676","6,941,072","7,044,008","7,158,024","7,278,717"
11,Arkansas,"2,915,918","2,916,031","2,921,964","2,940,667","2,952,164","2,959,400","2,967,392","2,978,048","2,989,918","3,001,345","3,009,733","3,017,804"
12,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
13,Colorado,"5,029,196","5,029,319","5,047,349","5,121,108","5,192,647","5,269,035","5,350,101","5,450,623","5,539,215","5,611,885","5,691,287","5,758,736"
14,Connecticut,"3,574,097","3,574,147","3,579,114","3,588,283","3,594,547","3,594,841","3,594,524","3,587,122","3,578,141","3,573,297","3,571,520","3,565,287"
15,Delaware,"897,934","897,937","899,593","907,381","915,179","923,576","932,487","941,252","948,921","956,823","965,479","973,764"
16,District of Columbia,"601,723","601,767","605,226","619,800","634,924","650,581","662,328","675,400","685,815","694,906","701,547","705,749"

In [6]:
state_pop1.columns

Index(['table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [7]:
state_pop1.rename(columns={"table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)":"State", "Unnamed: 12":"2019"})

,State,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,2019
2,NaN,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"
10,Arizona,"6,392,017","6,392,288","6,407,172","6,472,643","6,554,978","6,632,764","6,730,413","6,829,676","6,941,072","7,044,008","7,158,024","7,278,717"
11,Arkansas,"2,915,918","2,916,031","2,921,964","2,940,667","2,952,164","2,959,400","2,967,392","2,978,048","2,989,918","3,001,345","3,009,733","3,017,804"
12,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
13,Colorado,"5,029,196","5,029,319","5,047,349","5,121,108","5,192,647","5,269,035","5,350,101","5,450,623","5,539,215","5,611,885","5,691,287","5,758,736"
14,Connecticut,"3,574,097","3,574,147","3,579,114","3,588,283","3,594,547","3,594,841","3,594,524","3,587,122","3,578,141","3,573,297","3,571,520","3,565,287"
15,Delaware,"897,934","897,937","899,593","907,381","915,179","923,576","932,487","941,252","948,921","956,823","965,479","973,764"
16,District of Columbia,"601,723","601,767","605,226","619,800","634,924","650,581","662,328","675,400","685,815","694,906","701,547","705,749"
17,Florida,"18,801,310","18,804,564","18,845,537","19,053,237","19,297,822","19,545,621","19,845,911","20,209,042","20,613,477","20,963,613","21,244,317","21,477,737"
18,Georgia,"9,687,653","9,688,729","9,711,881","9,802,431","9,901,430","9,972,479","10,067,278","10,178,447","10,301,890","10,410,330","10,511,131","10,617,423"
19,Hawaii,"1,360,301","1,360,307","1,363,963","1,379,329","1,394,804","1,408,243","1,414,538","1,422,052","1,427,559","1,424,393","1,420,593","1,415,872"
20,Idaho,"1,567,582","1,567,657","1,570,746","1,583,910","1,595,324","1,611,206","1,631,112","1,651,059","1,682,380","1,717,715","1,750,536","1,787,065"
21,Illinois,"12,830,632","12,831,572","12,840,503","12,867,454","12,882,510","12,895,129","12,884,493","12,858,913","12,820,527","12,778,828","12,723,071","12,671,821"
22,Indiana,"6,483,802","6,484,051","6,490,432","6,516,528","6,537,703","6,568,713","6,593,644","6,608,422","6,634,304","6,658,078","6,695,497","6,732,219"
23,Iowa,"3,046,355","3,046,871","3,050,745","3,066,336","3,076,190","3,092,997","3,109,350","3,120,960","3,131,371","3,141,550","3,148,618","3,155,070"
24,Kansas,"2,853,118","2,853,123","2,858,190","2,869,225","2,885,257","2,893,212","2,900,475","2,909,011","2,910,844","2,908,718","2,911,359","2,913,314"
25,Kentucky,"4,339,367","4,339,333","4,348,181","4,369,821","4,386,346","4,404,659","4,414,349","4,425,976","4,438,182","4,452,268","4,461,153","4,467,673"
26,Louisiana,"4,533,372","4,533,487","4,544,532","4,575,625","4,600,972","4,624,527","4,644,013","4,664,628","4,678,135","4,670,560","4,659,690","4,648,794"
27,Maine,"1,328,361","1,328,358","1,327,629","1,328,284","1,327,729","1,328,009","1,330,513","1,328,262","1,331,317","1,334,612","1,339,057","1,344,212"
28,Maryland,"5,773,552","5,773,794","5,788,645","5,839,419","5,886,992","5,923,188","5,957,283","5,985,562","6,003,323","6,023,868","6,035,802","6,045,680"
29,Massachusetts,"6,547,629","6,547,785","6,566,307","6,613,583","6,663,005","6,713,315","6,762,596","6,794,228","6,823,608","6,859,789","6,882,635","6,892,503"
30,Michigan,"9,883,640","9,884,116","9,877,510","9,882,412","9,897,145","9,913,065","9,929,848","9,931,715","9,950,571","9,973,114","9,984,072","9,986,857"
31,Minnesota,"5,303,925","5,303,927","5,310,828","5,346,143","5,376,643","5,413,479","5,451,079","5,482,032","5,522,744","5,566,230","5,606,249","5,639,632"
32,Mississippi,"2,967,297","2,968,130","2,970,548","2,978,731","2,983,816","2,988,711","2,990,468","2,988,471","2,987,938","2,988,510","2,981,020","2,976,149"
33,Missouri,"5,988,927","5,988,950","5,995,974","6,010,275","6,024,367","6,040,715","6,056,202","6,071,732","6,087,135","6,106,670","6,121,623","6,137,428"
34,Montana,"989,415","989,407","990,697","997,316","1,003,783","1,013,569","1,021,869","1,030,475","1,040,859","1,052,482","1,060,665","1,068,778"
35,Nebraska,"1,826,341","1,826,305","1,829,542","1,840,672","1,853,303","1,865,279","1,879,321","1,891,277","1,905,616","1,915,947","1,925,614","1,934,408"
36,Nevada,"2,700,551","2,700,677","2,702,405","2,712,730","2,743,996","2,775,970","2,817,628","2,866,939","2,917,563","2,969,905","3,027,341","3,080,156"
37,New Hampshire,"1,316,470","1,316,462","1,316,762","1,320,202","1,324,232","1,326,622","1,333,341","1,336,350","1,342,307","1,348,787","1,353,465","1,359,711"
38,New Jersey,"8,791,894","8,791,978","8,799,446","8,828,117","8,844,942","8,856,972","8,864,525","8,867,949","8,870,827","8,885,525","8,886,025","8,882,190"
39,New Mexico,"2,059,179","2,059,199","2,064,552","2,080,450","2,087,309","2,092,273","2,089,568","2,089,291","2,091,630","2,091,784","2,092,741","2,096,829"
40,New York,"19,378,102","19,378,144","19,399,878","19,499,241","19,572,932","19,624,447","19,651,049","19,654,666","19,633,428","19,589,572","19,530,351","19,453,561"
41,North Carolina,"9,535,483","9,535,751","9,574,323","9,657,592","9,749,476","9,843,336","9,932,887","10,031,646","10,154,788","10,268,233","10,381,615","10,488,084"
42,North Dakota,"672,591","672,576","674,715","685,225","701,176","722,036","737,401","754,066","754,434","754,942","758,080","762,062"
43,Ohio,"11,536,504","11,536,751","11,539,336","11,544,663","11,548,923","11,576,684","11,602,700","11,617,527","11,634,370","11,659,650","11,676,341","11,689,100"
44,Oklahoma,"3,751,351","3,751,582","3,759,944","3,788,379","3,818,814","3,853,214","3,878,187","3,909,500","3,926,331","3,931,316","3,940,235","3,956,971"
45,Oregon,"3,831,074","3,831,079","3,837,491","3,872,036","3,899,001","3,922,468","3,963,244","4,015,792","4,089,976","4,143,625","4,181,886","4,217,737"
46,Pennsylvania,"12,702,379","12,702,868","12,711,160","12,745,815","12,767,118","12,776,309","12,788,313","12,784,826","12,782,275","12,787,641","12,800,922","12,801,989"
47,Rhode Island,"1,052,567","1,052,964","1,053,959","1,053,649","1,054,621","1,055,081","1,055,936","1,056,065","1,056,770","1,055,673","1,058,287","1,059,361"
48,South Carolina,"4,625,364","4,625,366","4,635,649","4,671,994","4,717,354","4,764,080","4,823,617","4,891,938","4,957,968","5,021,268","5,084,156","5,148,714"
49,South Dakota,"814,180","814,198","816,166","823,579","833,566","842,316","849,129","853,988","862,996","872,868","878,698","884,659"
50,Tennessee,"6,346,105","6,346,276","6,355,311","6,399,291","6,453,898","6,494,340","6,541,223","6,591,170","6,646,010","6,708,799","6,771,631","6,829,174"
51,Texas,"25,145,561","25,146,091","25,241,971","25,645,629","26,084,481","26,480,266","26,964,333","27,470,056","27,914,410","28,295,273","28,628,666","28,995,881"
52,Utah,"2,763,885","2,763,891","2,775,332","2,814,384","2,853,375","2,897,640","2,936,879","2,981,835","3,041,868","3,101,042","3,153,550","3,205,958"
53,Vermont,"625,741","625,737","625,879","627,049","626,090","626,210","625,214","625,216","623,657","624,344","624,358","623,989"
54,Virginia,"8,001,024","8,001,049","8,023,699","8,101,155","8,185,080","8,252,427","8,310,993","8,361,808","8,410,106","8,463,587","8,501,286","8,535,519"
55,Washington,"6,724,540","6,724,540","6,742,830","6,826,627","6,897,058","6,963,985","7,054,655","7,163,657","7,294,771","7,423,362","7,523,869","7,614,893"
56,West Virginia,"1,852,994","1,853,018","1,854,239","1,856,301","1,856,872","1,853,914","1,849,489","1,842,050","1,831,023","1,817,004","1,804,291","1,792,147"
57,Wisconsin,"5,686,986","5,687,285","5,690,475","5,705,288","5,719,960","5,736,754","5,751,525","5,760,940","5,772,628","5,790,186","5,807,406","5,822,434"
58,Wyoming,"563,626","563,775","564,487","567,299","576,305","582,122","582,531","585,613","584,215","578,931","577,601","578,759"
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Puerto Rico,"3,725,789","3,726,157","3,721,525","3,678,732","3,634,488","3,593,077","3,534,874","3,473,232","3,406,672","3,325,286","3,193,354","3,193,694"
61,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
state_pop2 = state_pop1.dropna()

In [9]:
state_pop2

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"
10,Arizona,"6,392,017","6,392,288","6,407,172","6,472,643","6,554,978","6,632,764","6,730,413","6,829,676","6,941,072","7,044,008","7,158,024","7,278,717"
11,Arkansas,"2,915,918","2,916,031","2,921,964","2,940,667","2,952,164","2,959,400","2,967,392","2,978,048","2,989,918","3,001,345","3,009,733","3,017,804"
12,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
13,Colorado,"5,029,196","5,029,319","5,047,349","5,121,108","5,192,647","5,269,035","5,350,101","5,450,623","5,539,215","5,611,885","5,691,287","5,758,736"
14,Connecticut,"3,574,097","3,574,147","3,579,114","3,588,283","3,594,547","3,594,841","3,594,524","3,587,122","3,578,141","3,573,297","3,571,520","3,565,287"
15,Delaware,"897,934","897,937","899,593","907,381","915,179","923,576","932,487","941,252","948,921","956,823","965,479","973,764"
16,District of Columbia,"601,723","601,767","605,226","619,800","634,924","650,581","662,328","675,400","685,815","694,906","701,547","705,749"
17,Florida,"18,801,310","18,804,564","18,845,537","19,053,237","19,297,822","19,545,621","19,845,911","20,209,042","20,613,477","20,963,613","21,244,317","21,477,737"
18,Georgia,"9,687,653","9,688,729","9,711,881","9,802,431","9,901,430","9,972,479","10,067,278","10,178,447","10,301,890","10,410,330","10,511,131","10,617,423"
19,Hawaii,"1,360,301","1,360,307","1,363,963","1,379,329","1,394,804","1,408,243","1,414,538","1,422,052","1,427,559","1,424,393","1,420,593","1,415,872"
20,Idaho,"1,567,582","1,567,657","1,570,746","1,583,910","1,595,324","1,611,206","1,631,112","1,651,059","1,682,380","1,717,715","1,750,536","1,787,065"
21,Illinois,"12,830,632","12,831,572","12,840,503","12,867,454","12,882,510","12,895,129","12,884,493","12,858,913","12,820,527","12,778,828","12,723,071","12,671,821"
22,Indiana,"6,483,802","6,484,051","6,490,432","6,516,528","6,537,703","6,568,713","6,593,644","6,608,422","6,634,304","6,658,078","6,695,497","6,732,219"
23,Iowa,"3,046,355","3,046,871","3,050,745","3,066,336","3,076,190","3,092,997","3,109,350","3,120,960","3,131,371","3,141,550","3,148,618","3,155,070"
24,Kansas,"2,853,118","2,853,123","2,858,190","2,869,225","2,885,257","2,893,212","2,900,475","2,909,011","2,910,844","2,908,718","2,911,359","2,913,314"
25,Kentucky,"4,339,367","4,339,333","4,348,181","4,369,821","4,386,346","4,404,659","4,414,349","4,425,976","4,438,182","4,452,268","4,461,153","4,467,673"
26,Louisiana,"4,533,372","4,533,487","4,544,532","4,575,625","4,600,972","4,624,527","4,644,013","4,664,628","4,678,135","4,670,560","4,659,690","4,648,794"
27,Maine,"1,328,361","1,328,358","1,327,629","1,328,284","1,327,729","1,328,009","1,330,513","1,328,262","1,331,317","1,334,612","1,339,057","1,344,212"
28,Maryland,"5,773,552","5,773,794","5,788,645","5,839,419","5,886,992","5,923,188","5,957,283","5,985,562","6,003,323","6,023,868","6,035,802","6,045,680"
29,Massachusetts,"6,547,629","6,547,785","6,566,307","6,613,583","6,663,005","6,713,315","6,762,596","6,794,228","6,823,608","6,859,789","6,882,635","6,892,503"
30,Michigan,"9,883,640","9,884,116","9,877,510","9,882,412","9,897,145","9,913,065","9,929,848","9,931,715","9,950,571","9,973,114","9,984,072","9,986,857"
31,Minnesota,"5,303,925","5,303,927","5,310,828","5,346,143","5,376,643","5,413,479","5,451,079","5,482,032","5,522,744","5,566,230","5,606,249","5,639,632"
32,Mississippi,"2,967,297","2,968,130","2,970,548","2,978,731","2,983,816","2,988,711","2,990,468","2,988,471","2,987,938","2,988,510","2,981,020","2,976,149"
33,Missouri,"5,988,927","5,988,950","5,995,974","6,010,275","6,024,367","6,040,715","6,056,202","6,071,732","6,087,135","6,106,670","6,121,623","6,137,428"
34,Montana,"989,415","989,407","990,697","997,316","1,003,783","1,013,569","1,021,869","1,030,475","1,040,859","1,052,482","1,060,665","1,068,778"
35,Nebraska,"1,826,341","1,826,305","1,829,542","1,840,672","1,853,303","1,865,279","1,879,321","1,891,277","1,905,616","1,915,947","1,925,614","1,934,408"
36,Nevada,"2,700,551","2,700,677","2,702,405","2,712,730","2,743,996","2,775,970","2,817,628","2,866,939","2,917,563","2,969,905","3,027,341","3,080,156"
37,New Hampshire,"1,316,470","1,316,462","1,316,762","1,320,202","1,324,232","1,326,622","1,333,341","1,336,350","1,342,307","1,348,787","1,353,465","1,359,711"
38,New Jersey,"8,791,894","8,791,978","8,799,446","8,828,117","8,844,942","8,856,972","8,864,525","8,867,949","8,870,827","8,885,525","8,886,025","8,882,190"
39,New Mexico,"2,059,179","2,059,199","2,064,552","2,080,450","2,087,309","2,092,273","2,089,568","2,089,291","2,091,630","2,091,784","2,092,741","2,096,829"
40,New York,"19,378,102","19,378,144","19,399,878","19,499,241","19,572,932","19,624,447","19,651,049","19,654,666","19,633,428","19,589,572","19,530,351","19,453,561"
41,North Carolina,"9,535,483","9,535,751","9,574,323","9,657,592","9,749,476","9,843,336","9,932,887","10,031,646","10,154,788","10,268,233","10,381,615","10,488,084"
42,North Dakota,"672,591","672,576","674,715","685,225","701,176","722,036","737,401","754,066","754,434","754,942","758,080","762,062"
43,Ohio,"11,536,504","11,536,751","11,539,336","11,544,663","11,548,923","11,576,684","11,602,700","11,617,527","11,634,370","11,659,650","11,676,341","11,689,100"
44,Oklahoma,"3,751,351","3,751,582","3,759,944","3,788,379","3,818,814","3,853,214","3,878,187","3,909,500","3,926,331","3,931,316","3,940,235","3,956,971"
45,Oregon,"3,831,074","3,831,079","3,837,491","3,872,036","3,899,001","3,922,468","3,963,244","4,015,792","4,089,976","4,143,625","4,181,886","4,217,737"
46,Pennsylvania,"12,702,379","12,702,868","12,711,160","12,745,815","12,767,118","12,776,309","12,788,313","12,784,826","12,782,275","12,787,641","12,800,922","12,801,989"
47,Rhode Island,"1,052,567","1,052,964","1,053,959","1,053,649","1,054,621","1,055,081","1,055,936","1,056,065","1,056,770","1,055,673","1,058,287","1,059,361"
48,South Carolina,"4,625,364","4,625,366","4,635,649","4,671,994","4,717,354","4,764,080","4,823,617","4,891,938","4,957,968","5,021,268","5,084,156","5,148,714"
49,South Dakota,"814,180","814,198","816,166","823,579","833,566","842,316","849,129","853,988","862,996","872,868","878,698","884,659"
50,Tennessee,"6,346,105","6,346,276","6,355,311","6,399,291","6,453,898","6,494,340","6,541,223","6,591,170","6,646,010","6,708,799","6,771,631","6,829,174"
51,Texas,"25,145,561","25,146,091","25,241,971","25,645,629","26,084,481","26,480,266","26,964,333","27,470,056","27,914,410","28,295,273","28,628,666","28,995,881"
52,Utah,"2,763,885","2,763,891","2,775,332","2,814,384","2,853,375","2,897,640","2,936,879","2,981,835","3,041,868","3,101,042","3,153,550","3,205,958"
53,Vermont,"625,741","625,737","625,879","627,049","626,090","626,210","625,214","625,216","623,657","624,344","624,358","623,989"
54,Virginia,"8,001,024","8,001,049","8,023,699","8,101,155","8,185,080","8,252,427","8,310,993","8,361,808","8,410,106","8,463,587","8,501,286","8,535,519"
55,Washington,"6,724,540","6,724,540","6,742,830","6,826,627","6,897,058","6,963,985","7,054,655","7,163,657","7,294,771","7,423,362","7,523,869","7,614,893"
56,West Virginia,"1,852,994","1,853,018","1,854,239","1,856,301","1,856,872","1,853,914","1,849,489","1,842,050","1,831,023","1,817,004","1,804,291","1,792,147"
57,Wisconsin,"5,686,986","5,687,285","5,690,475","5,705,288","5,719,960","5,736,754","5,751,525","5,760,940","5,772,628","5,790,186","5,807,406","5,822,434"
58,Wyoming,"563,626","563,775","564,487","567,299","576,305","582,122","582,531","585,613","584,215","578,931","577,601","578,759"
60,Puerto Rico,"3,725,789","3,726,157","3,721,525","3,678,732","3,634,488","3,593,077","3,534,874","3,473,232","3,406,672","3,325,286","3,193,354","3,193,694"

In [10]:
state_pop2.reset_index()

,index,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
1,9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"
2,10,Arizona,"6,392,017","6,392,288","6,407,172","6,472,643","6,554,978","6,632,764","6,730,413","6,829,676","6,941,072","7,044,008","7,158,024","7,278,717"
3,11,Arkansas,"2,915,918","2,916,031","2,921,964","2,940,667","2,952,164","2,959,400","2,967,392","2,978,048","2,989,918","3,001,345","3,009,733","3,017,804"
4,12,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
5,13,Colorado,"5,029,196","5,029,319","5,047,349","5,121,108","5,192,647","5,269,035","5,350,101","5,450,623","5,539,215","5,611,885","5,691,287","5,758,736"
6,14,Connecticut,"3,574,097","3,574,147","3,579,114","3,588,283","3,594,547","3,594,841","3,594,524","3,587,122","3,578,141","3,573,297","3,571,520","3,565,287"
7,15,Delaware,"897,934","897,937","899,593","907,381","915,179","923,576","932,487","941,252","948,921","956,823","965,479","973,764"
8,16,District of Columbia,"601,723","601,767","605,226","619,800","634,924","650,581","662,328","675,400","685,815","694,906","701,547","705,749"
9,17,Florida,"18,801,310","18,804,564","18,845,537","19,053,237","19,297,822","19,545,621","19,845,911","20,209,042","20,613,477","20,963,613","21,244,317","21,477,737"
10,18,Georgia,"9,687,653","9,688,729","9,711,881","9,802,431","9,901,430","9,972,479","10,067,278","10,178,447","10,301,890","10,410,330","10,511,131","10,617,423"
11,19,Hawaii,"1,360,301","1,360,307","1,363,963","1,379,329","1,394,804","1,408,243","1,414,538","1,422,052","1,427,559","1,424,393","1,420,593","1,415,872"
12,20,Idaho,"1,567,582","1,567,657","1,570,746","1,583,910","1,595,324","1,611,206","1,631,112","1,651,059","1,682,380","1,717,715","1,750,536","1,787,065"
13,21,Illinois,"12,830,632","12,831,572","12,840,503","12,867,454","12,882,510","12,895,129","12,884,493","12,858,913","12,820,527","12,778,828","12,723,071","12,671,821"
14,22,Indiana,"6,483,802","6,484,051","6,490,432","6,516,528","6,537,703","6,568,713","6,593,644","6,608,422","6,634,304","6,658,078","6,695,497","6,732,219"
15,23,Iowa,"3,046,355","3,046,871","3,050,745","3,066,336","3,076,190","3,092,997","3,109,350","3,120,960","3,131,371","3,141,550","3,148,618","3,155,070"
16,24,Kansas,"2,853,118","2,853,123","2,858,190","2,869,225","2,885,257","2,893,212","2,900,475","2,909,011","2,910,844","2,908,718","2,911,359","2,913,314"
17,25,Kentucky,"4,339,367","4,339,333","4,348,181","4,369,821","4,386,346","4,404,659","4,414,349","4,425,976","4,438,182","4,452,268","4,461,153","4,467,673"
18,26,Louisiana,"4,533,372","4,533,487","4,544,532","4,575,625","4,600,972","4,624,527","4,644,013","4,664,628","4,678,135","4,670,560","4,659,690","4,648,794"
19,27,Maine,"1,328,361","1,328,358","1,327,629","1,328,284","1,327,729","1,328,009","1,330,513","1,328,262","1,331,317","1,334,612","1,339,057","1,344,212"
20,28,Maryland,"5,773,552","5,773,794","5,788,645","5,839,419","5,886,992","5,923,188","5,957,283","5,985,562","6,003,323","6,023,868","6,035,802","6,045,680"
21,29,Massachusetts,"6,547,629","6,547,785","6,566,307","6,613,583","6,663,005","6,713,315","6,762,596","6,794,228","6,823,608","6,859,789","6,882,635","6,892,503"
22,30,Michigan,"9,883,640","9,884,116","9,877,510","9,882,412","9,897,145","9,913,065","9,929,848","9,931,715","9,950,571","9,973,114","9,984,072","9,986,857"
23,31,Minnesota,"5,303,925","5,303,927","5,310,828","5,346,143","5,376,643","5,413,479","5,451,079","5,482,032","5,522,744","5,566,230","5,606,249","5,639,632"
24,32,Mississippi,"2,967,297","2,968,130","2,970,548","2,978,731","2,983,816","2,988,711","2,990,468","2,988,471","2,987,938","2,988,510","2,981,020","2,976,149"
25,33,Missouri,"5,988,927","5,988,950","5,995,974","6,010,275","6,024,367","6,040,715","6,056,202","6,071,732","6,087,135","6,106,670","6,121,623","6,137,428"
26,34,Montana,"989,415","989,407","990,697","997,316","1,003,783","1,013,569","1,021,869","1,030,475","1,040,859","1,052,482","1,060,665","1,068,778"
27,35,Nebraska,"1,826,341","1,826,305","1,829,542","1,840,672","1,853,303","1,865,279","1,879,321","1,891,277","1,905,616","1,915,947","1,925,614","1,934,408"
28,36,Nevada,"2,700,551","2,700,677","2,702,405","2,712,730","2,743,996","2,775,970","2,817,628","2,866,939","2,917,563","2,969,905","3,027,341","3,080,156"
29,37,New Hampshire,"1,316,470","1,316,462","1,316,762","1,320,202","1,324,232","1,326,622","1,333,341","1,336,350","1,342,307","1,348,787","1,353,465","1,359,711"
30,38,New Jersey,"8,791,894","8,791,978","8,799,446","8,828,117","8,844,942","8,856,972","8,864,525","8,867,949","8,870,827","8,885,525","8,886,025","8,882,190"
31,39,New Mexico,"2,059,179","2,059,199","2,064,552","2,080,450","2,087,309","2,092,273","2,089,568","2,089,291","2,091,630","2,091,784","2,092,741","2,096,829"
32,40,New York,"19,378,102","19,378,144","19,399,878","19,499,241","19,572,932","19,624,447","19,651,049","19,654,666","19,633,428","19,589,572","19,530,351","19,453,561"
33,41,North Carolina,"9,535,483","9,535,751","9,574,323","9,657,592","9,749,476","9,843,336","9,932,887","10,031,646","10,154,788","10,268,233","10,381,615","10,488,084"
34,42,North Dakota,"672,591","672,576","674,715","685,225","701,176","722,036","737,401","754,066","754,434","754,942","758,080","762,062"
35,43,Ohio,"11,536,504","11,536,751","11,539,336","11,544,663","11,548,923","11,576,684","11,602,700","11,617,527","11,634,370","11,659,650","11,676,341","11,689,100"
36,44,Oklahoma,"3,751,351","3,751,582","3,759,944","3,788,379","3,818,814","3,853,214","3,878,187","3,909,500","3,926,331","3,931,316","3,940,235","3,956,971"
37,45,Oregon,"3,831,074","3,831,079","3,837,491","3,872,036","3,899,001","3,922,468","3,963,244","4,015,792","4,089,976","4,143,625","4,181,886","4,217,737"
38,46,Pennsylvania,"12,702,379","12,702,868","12,711,160","12,745,815","12,767,118","12,776,309","12,788,313","12,784,826","12,782,275","12,787,641","12,800,922","12,801,989"
39,47,Rhode Island,"1,052,567","1,052,964","1,053,959","1,053,649","1,054,621","1,055,081","1,055,936","1,056,065","1,056,770","1,055,673","1,058,287","1,059,361"
40,48,South Carolina,"4,625,364","4,625,366","4,635,649","4,671,994","4,717,354","4,764,080","4,823,617","4,891,938","4,957,968","5,021,268","5,084,156","5,148,714"
41,49,South Dakota,"814,180","814,198","816,166","823,579","833,566","842,316","849,129","853,988","862,996","872,868","878,698","884,659"
42,50,Tennessee,"6,346,105","6,346,276","6,355,311","6,399,291","6,453,898","6,494,340","6,541,223","6,591,170","6,646,010","6,708,799","6,771,631","6,829,174"
43,51,Texas,"25,145,561","25,146,091","25,241,971","25,645,629","26,084,481","26,480,266","26,964,333","27,470,056","27,914,410","28,295,273","28,628,666","28,995,881"
44,52,Utah,"2,763,885","2,763,891","2,775,332","2,814,384","2,853,375","2,897,640","2,936,879","2,981,835","3,041,868","3,101,042","3,153,550","3,205,958"
45,53,Vermont,"625,741","625,737","625,879","627,049","626,090","626,210","625,214","625,216","623,657","624,344","624,358","623,989"
46,54,Virginia,"8,001,024","8,001,049","8,023,699","8,101,155","8,185,080","8,252,427","8,310,993","8,361,808","8,410,106","8,463,587","8,501,286","8,535,519"
47,55,Washington,"6,724,540","6,724,540","6,742,830","6,826,627","6,897,058","6,963,985","7,054,655","7,163,657","7,294,771","7,423,362","7,523,869","7,614,893"
48,56,West Virginia,"1,852,994","1,853,018","1,854,239","1,856,301","1,856,872","1,853,914","1,849,489","1,842,050","1,831,023","1,817,004","1,804,291","1,792,147"
49,57,Wisconsin,"5,686,986","5,687,285","5,690,475","5,705,288","5,719,960","5,736,754","5,751,525","5,760,940","5,772,628","5,790,186","5,807,406","5,822,434"
50,58,Wyoming,"563,626","563,775","564,487","567,299","576,305","582,122","582,531","585,613","584,215","578,931","577,601","578,759"
51,60,Puerto Rico,"3,725,789","3,726,157","3,721,525","3,678,732","3,634,488","3,593,077","3,534,874","3,473,232","3,406,672","3,325,286","3,193,354","3,193,694"

In [11]:
state_pop2.columns

Index(['table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [12]:
state_pop3 = state_pop2.rename(columns={"table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)":"State", "Unnamed: 12":"2019"})

In [13]:
state_pop3

,State,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,2019
8,Alabama,"4,779,736","4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
9,Alaska,"710,231","710,249","713,910","722,128","730,443","737,068","736,283","737,498","741,456","739,700","735,139","731,545"
10,Arizona,"6,392,017","6,392,288","6,407,172","6,472,643","6,554,978","6,632,764","6,730,413","6,829,676","6,941,072","7,044,008","7,158,024","7,278,717"
11,Arkansas,"2,915,918","2,916,031","2,921,964","2,940,667","2,952,164","2,959,400","2,967,392","2,978,048","2,989,918","3,001,345","3,009,733","3,017,804"
12,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
13,Colorado,"5,029,196","5,029,319","5,047,349","5,121,108","5,192,647","5,269,035","5,350,101","5,450,623","5,539,215","5,611,885","5,691,287","5,758,736"
14,Connecticut,"3,574,097","3,574,147","3,579,114","3,588,283","3,594,547","3,594,841","3,594,524","3,587,122","3,578,141","3,573,297","3,571,520","3,565,287"
15,Delaware,"897,934","897,937","899,593","907,381","915,179","923,576","932,487","941,252","948,921","956,823","965,479","973,764"
16,District of Columbia,"601,723","601,767","605,226","619,800","634,924","650,581","662,328","675,400","685,815","694,906","701,547","705,749"
17,Florida,"18,801,310","18,804,564","18,845,537","19,053,237","19,297,822","19,545,621","19,845,911","20,209,042","20,613,477","20,963,613","21,244,317","21,477,737"
18,Georgia,"9,687,653","9,688,729","9,711,881","9,802,431","9,901,430","9,972,479","10,067,278","10,178,447","10,301,890","10,410,330","10,511,131","10,617,423"
19,Hawaii,"1,360,301","1,360,307","1,363,963","1,379,329","1,394,804","1,408,243","1,414,538","1,422,052","1,427,559","1,424,393","1,420,593","1,415,872"
20,Idaho,"1,567,582","1,567,657","1,570,746","1,583,910","1,595,324","1,611,206","1,631,112","1,651,059","1,682,380","1,717,715","1,750,536","1,787,065"
21,Illinois,"12,830,632","12,831,572","12,840,503","12,867,454","12,882,510","12,895,129","12,884,493","12,858,913","12,820,527","12,778,828","12,723,071","12,671,821"
22,Indiana,"6,483,802","6,484,051","6,490,432","6,516,528","6,537,703","6,568,713","6,593,644","6,608,422","6,634,304","6,658,078","6,695,497","6,732,219"
23,Iowa,"3,046,355","3,046,871","3,050,745","3,066,336","3,076,190","3,092,997","3,109,350","3,120,960","3,131,371","3,141,550","3,148,618","3,155,070"
24,Kansas,"2,853,118","2,853,123","2,858,190","2,869,225","2,885,257","2,893,212","2,900,475","2,909,011","2,910,844","2,908,718","2,911,359","2,913,314"
25,Kentucky,"4,339,367","4,339,333","4,348,181","4,369,821","4,386,346","4,404,659","4,414,349","4,425,976","4,438,182","4,452,268","4,461,153","4,467,673"
26,Louisiana,"4,533,372","4,533,487","4,544,532","4,575,625","4,600,972","4,624,527","4,644,013","4,664,628","4,678,135","4,670,560","4,659,690","4,648,794"
27,Maine,"1,328,361","1,328,358","1,327,629","1,328,284","1,327,729","1,328,009","1,330,513","1,328,262","1,331,317","1,334,612","1,339,057","1,344,212"
28,Maryland,"5,773,552","5,773,794","5,788,645","5,839,419","5,886,992","5,923,188","5,957,283","5,985,562","6,003,323","6,023,868","6,035,802","6,045,680"
29,Massachusetts,"6,547,629","6,547,785","6,566,307","6,613,583","6,663,005","6,713,315","6,762,596","6,794,228","6,823,608","6,859,789","6,882,635","6,892,503"
30,Michigan,"9,883,640","9,884,116","9,877,510","9,882,412","9,897,145","9,913,065","9,929,848","9,931,715","9,950,571","9,973,114","9,984,072","9,986,857"
31,Minnesota,"5,303,925","5,303,927","5,310,828","5,346,143","5,376,643","5,413,479","5,451,079","5,482,032","5,522,744","5,566,230","5,606,249","5,639,632"
32,Mississippi,"2,967,297","2,968,130","2,970,548","2,978,731","2,983,816","2,988,711","2,990,468","2,988,471","2,987,938","2,988,510","2,981,020","2,976,149"
33,Missouri,"5,988,927","5,988,950","5,995,974","6,010,275","6,024,367","6,040,715","6,056,202","6,071,732","6,087,135","6,106,670","6,121,623","6,137,428"
34,Montana,"989,415","989,407","990,697","997,316","1,003,783","1,013,569","1,021,869","1,030,475","1,040,859","1,052,482","1,060,665","1,068,778"
35,Nebraska,"1,826,341","1,826,305","1,829,542","1,840,672","1,853,303","1,865,279","1,879,321","1,891,277","1,905,616","1,915,947","1,925,614","1,934,408"
36,Nevada,"2,700,551","2,700,677","2,702,405","2,712,730","2,743,996","2,775,970","2,817,628","2,866,939","2,917,563","2,969,905","3,027,341","3,080,156"
37,New Hampshire,"1,316,470","1,316,462","1,316,762","1,320,202","1,324,232","1,326,622","1,333,341","1,336,350","1,342,307","1,348,787","1,353,465","1,359,711"
38,New Jersey,"8,791,894","8,791,978","8,799,446","8,828,117","8,844,942","8,856,972","8,864,525","8,867,949","8,870,827","8,885,525","8,886,025","8,882,190"
39,New Mexico,"2,059,179","2,059,199","2,064,552","2,080,450","2,087,309","2,092,273","2,089,568","2,089,291","2,091,630","2,091,784","2,092,741","2,096,829"
40,New York,"19,378,102","19,378,144","19,399,878","19,499,241","19,572,932","19,624,447","19,651,049","19,654,666","19,633,428","19,589,572","19,530,351","19,453,561"
41,North Carolina,"9,535,483","9,535,751","9,574,323","9,657,592","9,749,476","9,843,336","9,932,887","10,031,646","10,154,788","10,268,233","10,381,615","10,488,084"
42,North Dakota,"672,591","672,576","674,715","685,225","701,176","722,036","737,401","754,066","754,434","754,942","758,080","762,062"
43,Ohio,"11,536,504","11,536,751","11,539,336","11,544,663","11,548,923","11,576,684","11,602,700","11,617,527","11,634,370","11,659,650","11,676,341","11,689,100"
44,Oklahoma,"3,751,351","3,751,582","3,759,944","3,788,379","3,818,814","3,853,214","3,878,187","3,909,500","3,926,331","3,931,316","3,940,235","3,956,971"
45,Oregon,"3,831,074","3,831,079","3,837,491","3,872,036","3,899,001","3,922,468","3,963,244","4,015,792","4,089,976","4,143,625","4,181,886","4,217,737"
46,Pennsylvania,"12,702,379","12,702,868","12,711,160","12,745,815","12,767,118","12,776,309","12,788,313","12,784,826","12,782,275","12,787,641","12,800,922","12,801,989"
47,Rhode Island,"1,052,567","1,052,964","1,053,959","1,053,649","1,054,621","1,055,081","1,055,936","1,056,065","1,056,770","1,055,673","1,058,287","1,059,361"
48,South Carolina,"4,625,364","4,625,366","4,635,649","4,671,994","4,717,354","4,764,080","4,823,617","4,891,938","4,957,968","5,021,268","5,084,156","5,148,714"
49,South Dakota,"814,180","814,198","816,166","823,579","833,566","842,316","849,129","853,988","862,996","872,868","878,698","884,659"
50,Tennessee,"6,346,105","6,346,276","6,355,311","6,399,291","6,453,898","6,494,340","6,541,223","6,591,170","6,646,010","6,708,799","6,771,631","6,829,174"
51,Texas,"25,145,561","25,146,091","25,241,971","25,645,629","26,084,481","26,480,266","26,964,333","27,470,056","27,914,410","28,295,273","28,628,666","28,995,881"
52,Utah,"2,763,885","2,763,891","2,775,332","2,814,384","2,853,375","2,897,640","2,936,879","2,981,835","3,041,868","3,101,042","3,153,550","3,205,958"
53,Vermont,"625,741","625,737","625,879","627,049","626,090","626,210","625,214","625,216","623,657","624,344","624,358","623,989"
54,Virginia,"8,001,024","8,001,049","8,023,699","8,101,155","8,185,080","8,252,427","8,310,993","8,361,808","8,410,106","8,463,587","8,501,286","8,535,519"
55,Washington,"6,724,540","6,724,540","6,742,830","6,826,627","6,897,058","6,963,985","7,054,655","7,163,657","7,294,771","7,423,362","7,523,869","7,614,893"
56,West Virginia,"1,852,994","1,853,018","1,854,239","1,856,301","1,856,872","1,853,914","1,849,489","1,842,050","1,831,023","1,817,004","1,804,291","1,792,147"
57,Wisconsin,"5,686,986","5,687,285","5,690,475","5,705,288","5,719,960","5,736,754","5,751,525","5,760,940","5,772,628","5,790,186","5,807,406","5,822,434"
58,Wyoming,"563,626","563,775","564,487","567,299","576,305","582,122","582,531","585,613","584,215","578,931","577,601","578,759"
60,Puerto Rico,"3,725,789","3,726,157","3,721,525","3,678,732","3,634,488","3,593,077","3,534,874","3,473,232","3,406,672","3,325,286","3,193,354","3,193,694"

In [14]:
state_pops = state_pop3[['State', '2019']]

In [15]:
state_pops

                   State        2019
8                Alabama   4,903,185
9                 Alaska     731,545
10               Arizona   7,278,717
11              Arkansas   3,017,804
12            California  39,512,223
13              Colorado   5,758,736
14           Connecticut   3,565,287
15              Delaware     973,764
16  District of Columbia     705,749
17               Florida  21,477,737
18               Georgia  10,617,423
19                Hawaii   1,415,872
20                 Idaho   1,787,065
21              Illinois  12,671,821
22               Indiana   6,732,219
23                  Iowa   3,155,070
24                Kansas   2,913,314
25              Kentucky   4,467,673
26             Louisiana   4,648,794
27                 Maine   1,344,212
28              Maryland   6,045,680
29         Massachusetts   6,892,503
30              Michigan   9,986,857
31             Minnesota   5,639,632
32           Mississippi   2,976,149
33              Missouri   6,137,428
34               Montana   1,068,778
35              Nebraska   1,934,408
36                Nevada   3,080,156
37         New Hampshire   1,359,711
38            New Jersey   8,882,190
39            New Mexico   2,096,829
40              New York  19,453,561
41        North Carolina  10,488,084
42          North Dakota     762,062
43                  Ohio  11,689,100
44              Oklahoma   3,956,971
45                Oregon   4,217,737
46          Pennsylvania  12,801,989
47          Rhode Island   1,059,361
48        South Carolina   5,148,714
49          South Dakota     884,659
50             Tennessee   6,829,174
51                 Texas  28,995,881
52                  Utah   3,205,958
53               Vermont     623,989
54              Virginia   8,535,519
55            Washington   7,614,893
56         West Virginia   1,792,147
57             Wisconsin   5,822,434
58               Wyoming     578,759
60           Puerto Rico   3,193,694

In [16]:
state_pops.to_csv('state_populations.csv', index=False,)